'use strict';
const fs              = require("fs");
const ejs             = require("ejs");
const Book            = require("./books/book.js");
const Person          = require("./person/Person");
const BookListView    = require("./books/bookListView");
const StudentListView = require("./Student/studentListView");
const LoansListView   = require("./Loans/LoanListView");

const TabManager = (function () {
    let manager;
    const tabs = {
        books   : {
            label   : "Books",
            listView: new BookListView()
        },
        students: {
            label   : "Students",
            listView: new StudentListView()
        },
        loans   : {
            label   : "Loans",
            listView: new LoansListView()
        }
    };


    function createInstance() {
        return {};
    }

    function renderTabContent() {
        //getting the active tab, this css class is generated by jquery-ui dependency
        let currentTab = $(".ui-state-active a").data("tab");
        tabs[currentTab].listView.render();
    }

    function render() {
        const template = fs.readFileSync('./templates/tabManager.ejs', 'utf-8');
        const html     = ejs.render(template, {
            tabs: tabs
        });
        $(window.document.body).append(html);

        //initialize tabs
        $("#tabs").tabs({
            active  : 0,
            create  : function (event, ui) {
                renderTabContent();
            },
            activate: function (event, ui) {
                renderTabContent();
            }
        });
    }

    return {
        getInstance: function () {
            if (!manager) {
                manager = createInstance();
                render();
            }
            return manager;
        }
    };
})();

module.exports = TabManager;