'use strict';
let fs = require("fs");
let ejs = require("ejs");
let Book = require("./book.js");
let Person = require("./person");
let BookListView = require("./bookListView");
let TabManager = (function () {
    let manager;
    let tabs = {
        books: {
            label: "Books",
            listView: BookListView.getInstance()
        },
        students: {
            label: "Students",
            listView: {
                render : function () {
                    let joro = new Person("Joro", "Batanov");
                    joro.show();
                }
            }
        },
        teachers: {
            label: "Teachers",
            listView: {
                render : function () {
                    window.alert("Rendering Teachers");
                }
            }
        }
    };


    function createInstance() {
        return {};
    }

    function renderTabContent() {
        //getting the active tab, this css class is generated by jquery-ui dependency
        let currentTab = $(".ui-state-active a").data("tab");
        tabs[currentTab].listView.render();
    }

    function render() {
        let template = fs.readFileSync('./templates/tabManager.ejs', 'utf-8');
        let html = ejs.render(template, {
            tabs: tabs
        });
        $(window.document.body).append(html);

        //initialize tabs
        $("#tabs").tabs({
            active: 0,
            create: function (event, ui) {
                renderTabContent();
            },
            activate: function(event, ui) {
                renderTabContent();
            }
        });
    }

    return {
        getInstance: function () {
            if (!manager) {
                manager = createInstance();
                render();
            }
            return manager;
        }
    };
})();

module.exports = TabManager;